ALTER TABLE PRODUCTOS ADD FECHA DATE;
UPDATE PRODUCTOS SET FECHA = CONCAT(ANO, '-', MES, '-', DIA);
ALTER TABLE PRODUCTOS DROP DIA, DROP MES, DROP ANO;
UPDATE PRODUCTOS SET ORIGEN = 'ESPAÑA'
WHERE ORIGEN = 'ESPANA';
SELECT * FROM PRODUCTOS;