SELECT *, DATEDIFF(CURDATE(), FECHAPEDIDO) AS 'DIAS TRANSCURRIDOS',
DAYNAME(FECHAPEDIDO) AS DIA,  DAYOFYEAR(FECHAPEDIDO) AS 'DIA DEL AÑO',
MONTHNAME(FECHAPEDIDO) AS 'MES',
ADDDATE(FECHAPEDIDO, INTERVAL 30 DAY) AS 'PRIMER VENCIMIENTO',
ADDDATE(FECHAPEDIDO, INTERVAL 2 MONTH) AS 'SEGUNDO VENCIMIENTO' 
FROM PEDIDOS_NEPTUNO;