use laboratorio;
SELECT *, ROUND (CARGO * 0.21, 2) AS IVA,
ROUND(CARGO * 1.21, 2) AS NETO,
FLOOR(ROUND(CARGO * 1.21, 2)) AS 'REDONDEO A FAVOR CLIENTE',
CEIL(ROUND(CARGO * 1.21, 2)) AS 'REDONDEO A FAVOR EMPRESA'
FROM PEDIDOS_NEPTUNO